### PR TITLE
Allow single-letter schemes (fixes #100)

### LINKED ISSUE #100: Single letter scheme gets ignored, leading to unexpected results
When running autolinker on a string like "a://ab.x.us" it ignores "a:" as a possible scheme and then detects "//ab.x.us" instead. this leads to unexpected linking for users. It should either allow single letter schemes, or not detect that URL at all.

### PR DESCRIPTION
**Pull request by dgrad**

### CODE REVIEW

**Comment by gregjacobs** [comment]
Cool, will check it out. Seem to remember there was some problem with single letter schemes in the past, but can't remember what that might have been.

Quick question since I'm not at a desktop right now: did you add a test or two to cover the change?

**Comment by dgrad** [comment]
I did now

**Comment by dgrad** [comment]
updated pull request based on your latest README additions about contributing

**Comment by gregjacobs** [comment]
Um, I should have merged this decades ago... Sorry!!!!!

Thanks though man, great job.

**Pull request merged**
