### PR TITLE
Should include a check mark in the parsed URL

### LINKED ISSUE #176: Does not match the entire URL when a check mark character is present
For example, this URL
https://gitlab.example.com/search?utf8=✓&search=mysearch&group_id=&project_id=42&search_code=true&repository_ref=master
which is a valid one, renders only
https://gitlab.example.com/search?utf8=
as clickable
ref : https://github.com/RocketChat/Rocket.Chat/issues/4350

### PR DESCRIPTION
**Pull request by olafleur**
This is a pull request to fix #176 and https://github.com/RocketChat/Rocket.Chat/issues/4350

### CODE REVIEW

**Comment by olafleur** [comment]
@gregjacobs ping ;)

**Comment by gregjacobs** [comment]
Hey, sry, thanks for the ping! 

Hmm, a check character is really valid in a url?? lol

**Comment by gregjacobs** [comment]
Just saw your link for rocket chat. Hmm, ok, if you say so!

**Comment by olafleur** [comment]
Yes, event GitHub uses it when you search for something on its site. :)

**Pull request merged**
