### PR TITLE
Initial phone number support

### PR DESCRIPTION
**Pull request by sherbondy**
Summary of changes:
- Added a Phone match class to capture phone number semantics (creates proper "tel:" link)
- Incorporated an admittedly-naive phone number regex into the MatchParser
- Added a few basic test cases to demonstrate the new functionality
- Attempted to comprehensively update the documentation to describe the new feature.

Feel free to suggest changes.

---

While implementing this addition, I couldn't help but think that it'd be really nice to restructure the MatchParser to make it more openly-extensible.

I think we could do some clever stuff to clean up the replace function so that it is less hard-coded.
Then we could open up the library so that users could incorporate their own arbitrary text-matcher functions (so long as they don't overlap with existing regexes patterns).

Would be great to discuss architecture tweaks over email / pair program some time.
Let me know.

Might start hacking on this sometime tomorrow.

Thanks a ton for making this library and sharing with the community.

Cheers,
Ethan

### CODE REVIEW

**Comment by sherbondy** [comment]
One possible quick-and-dirty way to implement open extension would be to give the `replace` method in `MatchParser.js` a fourth argument for a secondary replaceFunction which is called when no matches are found. Or could even do this in `linkifyStr`. Guess it depends if you want to encourage people to extend `Autolinker.match.Match` when they add custom matchers.

Also, realized I forgot to update `README.md` or regen the docs to reflect the changes. Can certainly do that and resubmit a pull request if you decide the phone number addition is worth incorporating upstream.

**Comment by gregjacobs** [comment]
Hey, sorry I haven't gotten a chance to look at this! Will try to check it out tomorrow night when I have a little time. Thanks for the submission tho!!

**Comment by Nytrm** [comment]
Looking forward for this functionality, is this tested yet?

**Comment by gregjacobs** [comment]
Hey, wow, so sorry I fell off the face of the earth for a couple months there.

Thanks so much for this PR though. I think you're absolutely right though that Autolinker should be extensible in that `Matcher` classes could be added with either their own Regex matcher or custom processor for particular match types. The one consequence might be that the input string would need to be scanned multiple times - one for each match type. Either way, I think it's worth it.

One thing: I removed the `preprocessFn`. This didn't seem necessary since one can just preprocess the text before passing to Autolinker. Also, added some initial support for international phone numbers.

Thousand apologies though that it took so long for me to actually get this functionality in here. And thanks again.

**Pull request merged**
