### PR TITLE
New features: TruncateMiddle and TruncateSmart

### PR DESCRIPTION
**Pull request by kafoso**
This PR is a response to: https://github.com/gregjacobs/Autolinker.js/issues/85

Two new options have been added:

1. **truncateMiddle**: (Boolean) When `true`, the ellipsis character(s) (e.g. "..") will be placed in the dead-center of a URL rather than at the end.
2. **truncateSmart**: (Boolean) When `true`, the ellipsis character(s) (e.g. "..") will be placed at a point in the URL making it somewhat human readable. Overrides `truncateMiddle`. Non-essential parts of the URL (like scheme (e.g. "https") and fragment (content after "#")) may be removed in order to make room for significant URL sections. The priority is as follows:

    [host > path = query > fragment > scheme]

I've created a new namespace in Autolinker, `Autolinker.addon`, where the logic for these truncation options are located; `Autolinker.addon.TruncateMiddle` and `Autolinker.addon.TruncateSmart`, respectively. I didn't feel these features fit in an existing namespace or placement within the Autolinker object, hence the reason for the new namespace.

Autolinker should be backward compatible with these new options. I.e. they should not change existing behavior.

Unit tests are included.

@gregjacobs @devonzara @simison

Could you guys have a look?

@gregjacobs

I have not updated the info in README.md. Could you please do that when merging?

Cheers.

### CODE REVIEW

**Comment by devonzara** [comment]
:+1: Looks good! However, you didn't update the Gruntfile. The built files don't include the new methods.

I'm a bit mixed on hashtags having such a low priority level in the smartTruncate, but either way this is far better than truncating the end of URLs. From what little testing I've done, it seems to work fairly well. :)

**Comment by kafoso** [comment]
@devonzara 
Right. I'll add the addons to the Gruntfile and create a new build sometime after work.

**Regarding fragments/bookmarks**

I understand your concern. However, bookmarks were never meant to be significant parts of URLs. They are page content references and are usually not part of a server request.

Some client application software, e.g. AngularJS, utilizes hashtags for routing. This, however, is a poor makeshift solution to a browser incompatibility problem with missing or only partial support of [`history.pushState`](http://caniuse.com/#search=history.pushState).

Nevertheless, most - let's call them "hashtag routing applications" - contain no or a very short `path` and/or `query` section, e.g. "/app#my/little/hashtag/route". `TruncateSmart` will still truncate that string in a nice fashion when using truncate lengths greater than the length of the `path` + `query` strings. E.g. "/app#my/little/hashtag/route" truncated to 20 characters becomes "/app#my/lit..g/route", which is still fairly readable.

**Comment by kafoso** [comment]
* Gruntfile.js: Added `src/addon/TruncateMiddle.js` and `src/addon/TruncateSmart.js`.
* Built distributable files.
* Tested manually and through tests that distributable files (`dist/Autolinker.js` and `dist/Autolinker.min.js`) work.

**Comment by devonzara** [comment]
Whoops, sorry, was super busy this past week. Anyway, :+1: I would love to see this merged. :)

**Comment by kafoso** [comment]
@devonzara Thanks! Me too!

@gregjacobs are you around?

**Comment by gregjacobs** [comment]
Hey guys,

This is great. Thanks for adding this @kafoso! I'd just like to add a little tweak to the api. I'm thinking something like this:

```javascript
// Current truncate option:
truncate: 32,

// With truncate location:
truncate: { length: 32, location: 'end' }  // or 'middle', or 'smart' - must default to 'end' for backwards compatibility
```

This would avoid a few boolean options for the truncate location where one may take precedence over the other, and force the user to decide on one :) What do you think? Would you want to implement that?

Just a couple of other quick things btw:

1. Instead of the `addon` namespace, let's put the TruncateMiddle and TruncateSmart strategies in a `truncate` namespace. I think that will make sense for the project going forward. Feel free to leave your name on it though of course - you earned it ;)
2. Since the TruncateMiddle and TruncateSmart strategies are simply functions rather than constructors/classes, we should name them starting with a lowercase letter (`truncateMiddle` and `truncateSmart`). 
3. Could add a `truncateEnd` function for completeness with the middle and smart strategies. This function can just call `Autolinker.Util.ellipsis()` behind the scenes as is already done in `AnchorTagBuilder`. 

Otherwise, great job!

**Comment by kafoso** [comment]
Sure thing. I'm quite busy this week, but I'll look into it as soon as I have time for it.

**Comment by gregjacobs** [comment]
Awesome, sounds good!

**Comment by gregjacobs** [comment]
Hey @kafoso, I finally have a bit of time to work on this so I'll add the changes. Thanks so much for your PR!

**Comment by kafoso** [comment]
Okay. Thanks, @gregjacobs !
I've been very busy with work and other projects, so I had to down-prioritize this one.
Cheers.

**Pull request merged**
