### PR TITLE
reorder apply filter

### LINKED ISSUE #207: buseung.kim@aaa.com is matched URL and Email
buseung.kim@aaa.com is email format, and Autolinker match `buseung.kim` as URL too.
The two matches has equal index, so, `compactMatches` method remove one.

So Autolinker needs to change the order of `compactMatches` method and` removeUnwantedMatches` method.

### PR DESCRIPTION
**Pull request by kbs0327**
fixed #207

### CODE REVIEW

**Comment by olafleur** [comment]
There seems to be a failing test : 
```
1) should NOT automatically link a hashtag that is actually a named anchor within a URL **when URL linking is turned off**

     Autolinker link() method hashtag linking

     Expected 'http://google.com/<a href="https://twitter.com/hashtag/link">#link</a>' to be 'http://google.com/#link'.
```

Could you take a look ?

Thanks for your contribution !

**Comment by kbs0327** [comment]
I rollback reorder methods and fix this problem with `compactMatches` method

**Comment by olafleur** [comment]
Thank you !

**Comment by gregjacobs** [comment]
Hey guys, thanks for the contribution! I can't remember why exactly I had that while loop, but I guess if no tests break then we might be okay, lol. Might just not be possible to have multiple overlapping matches?

**Pull request merged**
