### PR TITLE
feat(): add TikTok mentions and hashtags

### PR DESCRIPTION
**Pull request by tomas-mikula**
TikTok has also fixed url for:

- hashtags `https://www.tiktok.com/tag/` + hashtag
- mentions `https://www.tiktok.com/@` + mention

So we could add this functionality to support this network too.

### CODE REVIEW

**Comment by daliclass** [comment]
Nice - Looking forward to this feature :)

**Comment by sudpaw** [comment]
Awesome. Can we get this merged!

**Comment by Sharky1231** [comment]
@gregjacobs Could you please take a look?

**Comment by Sharky1231** [comment]
@olafleur Could you please take a look / review?

**Comment by gregjacobs** [comment]
Hey guys, so sorry for the delay on this. Great job adding this, and appreciate the contribution!

**Comment by gregjacobs** [comment]
Oof, can't release this change just yet. Had a bunch of failing tests, and seems Autolinker's CI integration shut down so we didn't see it on this PR. Fixing now

**Comment by gregjacobs** [comment]
Just realizing too: did you forget to push some files? For instance, I don't see any changes to mention-matcher.ts for a TikTok regexp

**Comment by gregjacobs** [comment]
Ok I fixed things up and released as v3.15.0 👍

**Pull request merged**
