### PR TITLE
Helping to create the official package for Meteor.com

### PR DESCRIPTION
**Pull request by engelgabriel**
Hi, we are trying to help the best JS lib we use and love to have their own official packedege suport for Meteor.com

Now many good libraries have their own official packages

https://atmospherejs.com/?q=official

This PR adds the necessary files to start the process.

MeteorCommunity/discussions#14

If you accept, I'll help you all the way.

### CODE REVIEW

**Comment by gregjacobs** [comment]
Hey @engelgabriel, so sorry for the late response! I didn't really know anything about Meteor until I started researching just now, but seems cool. 

Is this PR def still needed / up to date though? The second link you provided seems to say that wrapper libraries that add Meteor support are automatically updated as of September 2015. I'm just wondering if Autolinker needs the official support for sure or not. If so, I'll def merge.

Just a quick question on your PR otherwise. Should `helpers.js` register the template with the name 'autolink' or 'autolinker'? Also, Autolinker doesn't have an `outputMarkdown` option (line 13 of `helpers.js`). Is something like that needed? I'd imagine not since markdown supports HTML, but just curious.

**Comment by engelgabriel** [comment]
Please merge the PR and I'll help with the rest of the process. I believe it is still better to have the offical package than just a third party wrapper.

**Comment by gregjacobs** [comment]
kk, you got it! Enjoy :)

**Comment by engelgabriel** [comment]
Can you please create and account at https://www.meteor.com/ and send me? I'll add you as owner of the organization "autolinker".

**Comment by gregjacobs** [comment]
Hey, added account. username: gregjacobs

**Pull request merged**
