### PR TITLE
support for accented characters in domain name

### PR DESCRIPTION
**Pull request by urish**
including unit-tests

### CODE REVIEW

**Comment by gregjacobs** [comment]
You. are. the. man.

Only question: do the diacritics need to be URL encoded?

Also, we might want to add a test or two checking that diacritics are matched inside the path, query string, and hash parts of URLs

**Comment by urish** [comment]
Thanks :)

With chrome it works without the IDN / URL encoding - the browser automatically takes care of that for us. I can check with Firefox / Edge if you are interested.

Well, I haven't added matching within the path / query / hash parts - if you are interested, I can try to add them as well (the domain is sufficient for my needs right now)

**Comment by urish** [comment]
Yay!

**Comment by gregjacobs** [comment]
Yes, finally, sorry for uber long delay lol

**Pull request merged**
