### PR TITLE
Fix regex for IP addresses

### PR DESCRIPTION
**Pull request by olafleur**
I just found an error in the stuff that I implemented.

The url http://1.2.3.4.5 is not a valid IP address so it shoud not be clickable

(it seems that GitHub also does that error ;) )

### CODE REVIEW

**Comment by gregjacobs** [comment]
Hehe, thanks!

**Comment by olafleur** [comment]
No problem, thanks to you! :)

**Comment by olafleur** [comment]
Would it be possible to do a 0.28.1 release with that fix?

**Comment by gregjacobs** [comment]
Whoops, so sorry! Doing now

**Comment by gregjacobs** [comment]
Done

**Comment by olafleur** [comment]
Ha! Ha! No stress, thanks a lot !

**Pull request merged**
