### PR TITLE
Adding capability to include extensions and exclude the big numbers

### PR DESCRIPTION
**Pull request by pratyushtewari**

### CODE REVIEW

**Comment by olafleur** [comment]
A few questions for you :
1) Is the # always needed at the end of the extension ? Some references tell that simply to have a comma and then a number after treats its as an extension.
2) Is it always a coma? In some cases, I think the correct syntax is `;ext=123` (looks like it is platform-dependent or something like it).

**Comment by olafleur** [comment]
However, I think this pull request could be merged anyway, as it is already an improvement over the old state (previously it did not recognize extensions at all).
These questions that popped into my mind may generate some reflection on how we could improve the solution.

**Comment by pratyushtewari** [comment]
@olafleur you are right. I think we can improve it a little more and make it more generic. Also, I checked that there could be more than one pause (, or ;) to increase the pause. Let me see If I can add this as well.

**Comment by pratyushtewari** [comment]
@olafleur I have updated the pull req to include numbers with multiple , or ; as part of the extension.

**Comment by olafleur** [comment]
Thanks a lot for your contribution !

**Comment by tangkunyin** [comment]
@ericfong Did your problem solved?  and how to customize phone Regex external

**Pull request merged**
