### PR TITLE
Upgrade to TypeScript 4

### PR DESCRIPTION
**Pull request by gregjacobs**

### CODE REVIEW

**Comment by olafleur** [comment]
Nice! LGTM! Is there a reason why you upgrade to 4.0.0 but not to 4.2.3 ?

**Comment by gregjacobs** [comment]
Awesome! 

And great question :) I just put "^4.0.0" in the package.json file so I didn't have to figure out the latest version, and yarn actually resolved that to 4.2.3 so should be all good 👍 I could have put "^4.2.3" into package.json though! I'll make that update real quick

**Comment by gregjacobs** [comment]
Done!

**Comment by olafleur** [comment]
Super!

**Comment by gregjacobs** [comment]
Just merged. Thanks for starting this one off!

**Pull request merged**
