### PR TITLE
Exclude invalid characters right after TLD in detected URLs

### PR DESCRIPTION
**Pull request by dgrad**
If in a detected URL, there are invalid characters right after the TLD, exclude them from the link.

Examples:
```
1. Check out google.com's design!
2. Check out www.google.com's design!
3. Check out www.google.com/foo's design!
4. Check out http://www.google.com's design!
```
Results:
```
1. Check out <a href="http://google.com">google.com</a>'s design!
2. Check out <a href="http://www.google.com">www.google.com</a>'s design!
3. Check out <a href="http://www.google.com/foo's">www.google.com/foo's</a> design!
4. Check out <a href="http://www.google.com">http://www.google.com</a>'s design!
```
Explained:
1. Because `'` is not a valid character right after the ".com", it's excluded along with everything else following it
2. Same as 1 for www URL
3. The character right after ".com" is '/', which is valid. Nothing done in this case
4. Same as 1 for URL with protocol

Edit: rule now applies to URLs with explicit protocol

### CODE REVIEW

**Comment by gregjacobs** [comment]
Hey, thanks for this PR! So sorry for the late reply. 

Quick question: Why allow the apostrophe after google.com in the full protocol example? (#4)

**Comment by dgrad** [comment]
I just followed the existing logic where certain checks are skipped on the full protocol case (I thought it's on the assumption that full protocol mean user wants it all to be a link)

**Comment by gregjacobs** [comment]
Hmm, yeah, ok, I thought that might have been why. Was wondering if there was another reason that I might have missed though. Let's do that - exclude the apostrophe from domain-name-only matches with a protocol. I think that would make sense. What do you think?

**Comment by dgrad** [comment]
I agree. Pushed the change to include the protocol cases.

**Comment by dgrad** [comment]
updated pull request based on your latest README additions about contributing

**Comment by Jake0oo0** [comment]
:+1: Would love to see this merged soon <3

**Comment by dgrad** [comment]
any update on merging this?

**Comment by gregjacobs** [comment]
Yes, ugh, sorry again! Life too busy.. I need a vacation!!

Great job on this though, thank you for the contribution!

**Pull request merged**
