### PR TITLE
Support scheme url starting with emoji

### PR DESCRIPTION
**Pull request by caiofct**
This PR is a fix for https://github.com/gregjacobs/Autolinker.js/issues/399. It essentially allows a schema url to start with any char including an emoji.

### CODE REVIEW

**Comment by caiofct** [comment]
@gregjacobs This is the new PR. Sorry about the trouble.

**Comment by gregjacobs** [comment]
Hey @caiofct. Sorry for the delay.

Unfortunately I don't think this is the correct fix (although it works at the moment, unexpectedly 😄 ). I'm looking more into it now though. 

We don't want to conceptually allow emojis to be valid scheme characters because a scheme (like `http` or `https`) would always be only ascii letters or numbers. I think instead, when we encounter an emoji, we want to skip over it and put the state machine back into the "no match" state. I'll play with it a bit.

Best,
Greg

**Comment by caiofct** [comment]
Hey @gregjacobs any luck on this issue?

> Hey @caiofct. Sorry for the delay.
> 
> Unfortunately I don't think this is the correct fix (although it works at the moment, unexpectedly 😄 ). I'm looking more into it now though.
> 
> We don't want to conceptually allow emojis to be valid scheme characters because a scheme (like `http` or `https`) would always be only ascii letters or numbers. I think instead, when we encounter an emoji, we want to skip over it and put the state machine back into the "no match" state. I'll play with it a bit.
> 
> Best, Greg

**Comment by gregjacobs** [comment]
Hey @caiofct, I ended up fixing this in 4.0.1. Try that out :) 

Best,
Greg

**Pull request closed without merging**
