### PR TITLE
hashtag regex proposal.

### PR DESCRIPTION
**Pull request by armator**
the library couldn't capture non-english hashtags before. (e.g. #NERDESİN because of the İ character inside the hashtag.)

changed \w with \S so that any non-space character will be captured as hashtag.

( and thanks for the library! :) )

### CODE REVIEW

**Comment by simison** [comment]
`#hashtag1, #hashtag2` probably should skip `,` tho?

**Comment by armator** [comment]
They shouldn't skip, as you can test it on twitter

**Comment by armator** [comment]
Sorry sorry i got it you mean comma not numbers... hmm i'll think about it

**Comment by simison** [comment]
also `?;` etc

**Comment by armator** [comment]
Allright. I ll examine this https://github.com/twitter/twitter-text/blob/master/js/twitter-text.js 
And hopefully come with a nicer solution soon.

**Comment by olafleur** [comment]
Hi @armator ! What's the status for this? Can I help you with something?

Something that really helps to review a pull request is for the contributor to provide tests that show the new behaviour. If you need help with that, let me know !

**Comment by armator** [comment]
Hi,

This was a year ago, and I had solved my problem with twitter's libraries then. I couldn't contribute to this, because of the travis error sorry. I think this should be closed.

**Pull request closed without merging**
